services:
  ai-backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: rkumar0206/ai-backend:v1.0.0
    container_name: ai-backend
    env_file:
      - .env
    environment:
      DB_URL: 'jdbc:postgresql://ai-db:5432/ai_projects_db'
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MODEL: ${MODEL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - "7070:7070"
    depends_on:
      - ai-db
    networks:
      - ai-network

  ai-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: rkumar0206/ai-db:v1.0.0
    container_name: ai-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
    name: ai-network

volumes:
  pgdata:
    driver: local